[build]
publish = "public"
command = "GIT_COMMIT_SHA=`git rev-parse --verify HEAD` GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD` hugo"

[context.production.environment]
HUGO_VERSION = "0.67.1"
HUGO_ENV = "production"
